title: Portable-CELLxGENE
description: Documentation for Portable-CELLxGENE
theme: just-the-docs

url: https://george-hall-ucl.github.io/Portable-CELLxGENE-Docs
favicon_ico: "/assets/images/favicon_new_export_small.svg"

color_scheme: yellow

head_custom: _includes/head_custom.html
